ForestAdmin/toolbelt

CHANGELOG.md
package.json
yarn.lock

…d you mean ...?" to correct the user input

[+] Prompt - Add the `@oclif/plugin-not-found` plugin which print "did you mean ...?" to correct the user input

---

.gitignore
CHANGELOG.md

iml files come from IDE and should never be pushed.

[-] Technical - Ignore .iml files

---

CHANGELOG.md
package.json

… warns when a new version is available.

[+] Versioning - Configure the `warn-if-update-available` plugin that warns when a new version is available

---

CHANGELOG.md
test/services/authenticator.test.js

This PR clean ./test/services/tokens content to avoid undesired files in the working copy.

[-] Technical - Clean temporary tests files.

---

CHANGELOG.md
src/abstract-authenticated-command.js
src/commands/environments/copy-layout.js
src/commands/environments/delete.js
src/commands/user.js
src/services/authenticator.js
src/services/prompter.js

[-] Logs - Remove worrisome emojis (such as fire and skulls) from error messages

---

CHANGELOG.md
src/abstract-authenticated-command.js
src/commands/login.js
src/services/authenticator.js

This PR ask for credentials when needed.
It's needed when the user performs a login-required command.
Note: All commands require login except `forest login` and `forest user`.

[+] Ask credentials when a command requires it.

---

CHANGELOG.md
package.json
src/commands/environments.js
src/commands/environments/copy-layout.js
src/commands/environments/create.js
src/commands/environments/delete.js
src/commands/environments/get.js
src/config.js
src/services/environment-manager.js
src/services/project-manager.js
src/services/with-current-project.js
test/commands/environments/delete.test.js
test/commands/environments/get.test.js
yarn.lock

See: https://app.clickup.com/t/3mgbn7 & https://github.com/ForestAdmin/forestadmin-server/pull/968
It considers:
1. `projectId` param.
2. then corresponding to `.env` file.
3. then all projects the user has created.

[-] Commands - ease the selection of project (1)

---

CHANGELOG.md
test/commands/environments.test.js
test/commands/login.test.js
test/commands/test-cli.js
test/fixtures/dialogs.js
test/fixtures/envs.js
test/fixtures/nocks.js

This PR add the following test: environments.test.js

[+] Tests - Add test for `forest environments` command

---

CHANGELOG.md
src/services/authenticator.js

Few changes are made in order to be simple.

[*] Logout - Display an explicit message when lumber is still connected.

---

CHANGELOG.md
src/commands/init.js

https://app.clickup.com/t/4wman4

feat(init command): create the init command with the login 1st step (#4wman4)

---

CHANGELOG.md
src/commands/branch.js
src/services/branch-manager.js
test/commands/branch.test.js
test/fixtures/api.js

feat(branch-command): add branch deletion command

---

src/services/spinner.js

fix(spinner): remove unneeded check on attachToPromise

---

src/commands/init.js
src/services/environment-manager.js
src/services/spinner.js
src/services/spinners.js
src/services/with-current-project.js

https://app.clickup.com/t/4wmbcj

feat(init-command): create the user development environment (#4wmbcj)

---

package.json

chore(ci): fix ci publish removing useless postpack/prepack

---

test/commands/init.test.js

chore: add init command test file skeleton

---

src/services/spinner.js
test/services/spinner.test.js

fix(spinner): fix cli lock on spinner pause

---

package.json
src/commands/init.js
src/utils/key-generator.js
yarn.lock

https://app.clickup.com/t/4wmbgy

feat(init-command): auto-fill or display environment variables (#4wmbgy)

---

test/commands/init.test.js
test/fixtures/api.js

chore: add init command login related tests

---

src/commands/init.js

chore(init-command): properly exit process on error

---

src/services/spinner.js

fix(spinner): avoid promise failures on paused spinner

---

src/commands/init.js
src/services/init-manager.js
src/services/spinner.js
test/commands/init.test.js

feat(init-command): refact the init command file

---

src/abstract-authenticated-command.js
src/services/authenticator.js

https://app.clickup.com/t/54r8q3

fix(authentication): fix login and logout messages (#54r8q3)

---

src/commands/init.js
src/services/init-manager.js
src/services/with-current-project.js
src/utils/error.js

fix(init-command): fix error handling

---

test/commands/init.test.js
test/commands/test-cli-errors.js
test/commands/test-cli.js
test/fixtures/api.js

chore: add init command project selection related tests

---

src/commands/branch.js
src/commands/environments.js
src/commands/environments/copy-layout.js
src/commands/environments/create.js
src/commands/environments/delete.js
src/commands/environments/get.js
src/commands/environments/update.js
src/commands/login.js
src/commands/logout.js
src/commands/projects.js
src/commands/projects/get.js
src/commands/schema/apply.js
src/commands/switch.js
src/commands/user.js

https://app.clickup.com/t/4yh6hw

fix: homogenize the format of the command descriptions

---

test/commands/init.test.js
test/fixtures/api.js

chore: add last init tests

---

package.json
src/services/logger.js
yarn.lock

chore(logger): remove winston dependency and use lumber-inspired homemade logger

---

src/abstract-authenticated-command.js
src/commands/branch.js
src/commands/environments/copy-layout.js
src/commands/environments/create.js
src/commands/environments/delete.js
src/commands/init.js
src/commands/schema/apply.js
src/commands/switch.js
src/services/apimap-sorter.js
src/services/environment-manager.js
src/services/job-state-checker.js
src/services/schema-sender.js
test/commands/branch.test.js
test/commands/environments/copy-layout.test.js
test/commands/environments/delete.test.js
test/commands/init.test.js
test/commands/schema/apply.test.js
test/commands/switch.test.js

https://app.clickup.com/t/4ygzep

fix: homogenize all displayed error messages style

---

src/commands/switch.js

fix(branch): fix switch command when environment has no current branch

---

package.json

Origin of the regression:
https://github.com/ForestAdmin/toolbelt/commit/0a666aee6d6edefeae7dbf23f6292335f99abb62
(I though all this was useless, but it is apparently not)
Clickup task:
https://app.clickup.com/t/5mnnf9

fix(commands): make each commands run as expected

---

src/commands/push.js
src/services/branch-manager.js
test/commands/environments.test.js
test/commands/push.test.js
test/fixtures/api.js

[Clickup card](https://app.clickup.com/t/56rqkb)
linked to ForestAdmin/forestadmin-server#1206

feat(command): add new push branch command

---

src/commands/environments/delete.js
src/services/environment-manager.js
test/commands/environments/delete.test.js
test/fixtures/api.js

chore(environment-remover): no longer expect a jobId on environment removal

---

src/commands/push.js
src/services/branch-manager.js
test/commands/push.test.js

fix(commands): update misleading error message for push command

---

src/services/branch-manager.js
test/fixtures/api.js

fix(push): push now uses a post instead of a put

---

src/utils/messages.js

Signed-off-by: Guillaume Deslandes <guillaumed@forestadmin.com>

fix(commands): remove Slack reference in error messages

---

src/services/init-manager.js

Signed-off-by: Guillaume Deslandes <guillaumed@forestadmin.com>

fix(commands): add newline at end of generated `.env` file

---

package.json

test: add `runInBand` option to jest to avoid concurrency issues

---

src/commands/init.js
src/services/project-manager.js
src/services/with-current-project.js
test/commands/init.test.js
test/fixtures/api.js

feat: add includeLegacy parameter to project by env secret retrieval

---

test/commands/init.test.js
test/commands/schema/apply.test.js
test/commands/test-cli-auth-token.js
test/commands/test-cli-errors.js
test/commands/test-cli-fs.js
test/commands/test-cli.js
test/services/authenticator.test.js

fix(test): fix randomly failing tests

---

src/commands/init.js
test/commands/init.test.js

Linked to: CU-7arnfn
New link is still dead, but complies with specs. See linked card for validation.
New documentation will be published soon.

docs(links): fix dead link in init command

---

.github/PULL_REQUEST_TEMPLATE.md

chore: change pull request template

---

src/commands/init.js
test/commands/init.test.js

fix: change link to docs in the init command

---

package.json
test/commands/schema/apply.test.js
test/commands/test-cli-std.js
test/services/spinner.test.js
yarn.lock

test: fix random test errors

---

.travis.yml
package.json

test(coverage): transmit coverage to Code Climate

---

.travis.yml

ci: add skip_cleanup back to avoid build fail

---

src/commands/push.js
test/commands/push.test.js

fix(push-command): allow project to be passed in as argument using --projectId or -p

---

src/commands/deploy.js
test/commands/deploy.test.js

fix(deploy-command): allow project to be passed in as argument using --projectId or -p

---

package.json
yarn.lock

Fixes #126 by specifying commit hash explicitly.

fix: prevent installation error due to premature evaluation caused by a dependency

---

bin/run
src/commands/branch.js
src/commands/deploy.js
src/commands/environments.js
src/commands/init.js
src/commands/push.js
src/commands/switch.js
src/commands/user.js
src/context/application-context.js
src/context/index.js
src/context/init.js
src/index.js
test/commands/test-cli.js
test/context/application-context.unit.test.js

refactor: add an application context to be able to unit test services

---

package.json
yarn.lock

chore: simplify development of test by providing type checking and suggestions

---

src/services/api.js

To remove code duplication detected in my other PR

refactor: remove code duplication on http headers initialization

---

test/commands/test-cli-std.js
test/commands/test-cli.js

test: improve output when tests fail

---

.travis.yml

chore: allow to release beta versions

---

src/abstract-authenticated-command.js
src/commands/branch.js
src/commands/deploy.js
src/commands/environments.js
src/commands/init.js
src/commands/login.js
src/commands/logout.js
src/commands/push.js
src/commands/schema/apply.js
src/commands/switch.js
src/commands/user.js
test/commands/environments/copy-layout.test.js
test/commands/test-cli-std.js
test/commands/test-cli.js
test/fixtures/api.js

fix: error when preparing the release

---

src/serializers/schema.js

fix: serialize hooks information with schema:apply

---

.github/workflows/build.yml

chore(release): fix npm release with the new CI

---

commitlint.config.js

ci: allow longer commit messages

---

src/commands/logout.js
test/commands/logout.test.js

fix(logout): logout command now works as expected

---

src/commands/deploy.js
test/commands/deploy.test.js
test/fixtures/api.js

fix(dwo): allow to deploy on remote non production reference environment

---

src/serializers/schema.js

fix: add missing keys isReadOnly for actions fields, isPrimaryKey and foreignAndPrimaryKey for fields

---

package.json
src/renderers/environment.js
src/renderers/project.js
yarn.lock

Fix https://github.com/ForestAdmin/toolbelt/issues/126

fix: update cli-table dependency

---

.releaserc.js

chore(force-release): add force-release tag

---

src/abstract-authenticated-command.js
src/abstract-command.js
src/commands/branch.js
src/commands/schema/update.js
src/index.js
test/commands/environments/update.test.js
test/commands/schema/update.test.js
test/commands/test-cli-auth-token.js
test/commands/test-cli-command.js
test/commands/test-cli-dependencies.js
test/commands/test-cli-errors.js
test/commands/test-cli.js

draft test way

---

src/commands/schema/apply.js
test/commands/schema/apply.test.js
test/fixtures/files.js

fix: accept new meta key format for forestadmin schema

---

test/services/prompter/inquirer.test.js

chore: test inquirer

---

src/commands/branch.js
src/commands/deploy.js
src/commands/environments.js
src/commands/environments/copy-layout.js
src/commands/environments/create.js
src/commands/init.js
src/commands/push.js

fix: validate that project id is an integer instead of a string

---

package.json
src/commands/environments/get.js
src/context/command-project-create-plan.js
src/context/command-projects-common-plan.js
src/context/constants-plan.js
src/context/constants.js
src/context/dependencies-plan.js
src/context/env-plan.js
src/context/plan.js
src/context/services-plan.js
src/services/authenticator.js
src/services/dumper/dumper.js
test/services/analyzer/dumper.test.js
test/services/analyzer/dumper.unit.test.js
test/services/authenticator.unit.test.js
yarn.lock

feat: get token from forest folder

---

package.json
src/config.js
src/context/command-project-create-plan.js
src/context/env-plan.js
src/context/plan.js
yarn.lock

chore: drop external config

---

src/services/authenticator.js
test/services/authenticator.unit.test.js

fix: save token in forest.d folder

---

src/services/authenticator.js
test/services/authenticator.unit.test.js

fix: logout also logout from forest.d folder

---

Dockerfile
README.md
src/context/env-plan.js
src/services/dumper/dumper.js
src/services/dumper/templates/app/Dockerfile.hbs
src/services/dumper/templates/app/docker-compose.hbs
src/services/oidc/authenticator.js
test/commands/init.test.js
test/commands/login.test.js
test/commands/projects/create.test.js
test/commands/schema/apply.test.js
test/services/oidc/authenticator.unit.test.js

chore: add Dockerfile to build command line inside docker

---

test/services/analyzer/dumper-sequelize.test.js

chore(force-release): remove useless code

---

package.json
yarn.lock

chore(force-release): update lodash to 4.17.21

---

src/services/dumper/dumper.js

chore(force-release): use forest express sequelize/mongoose v8 for new projects

---

src/services/schema/update/analyzer/database-analyzer.js
src/services/schema/update/database.js
test/services/analyzer/database-analyzer-mongo.test.js
test/services/analyzer/helpers/mongo-helper.js
test/services/database.unit.test.js

fix: handle properly mongo connection close

---

src/commands/projects/create.js
test/commands/projects/create.test.js

fix: transmit databaseSchema option to database connection

---

src/services/dumper/templates/app/routes/route.hbs
test/services/analyzer/expected/sequelize/dumper-output/export.expected.route.js

fix: avoid details route conflicting with count when overriding details route

---

test/services/analyzer/dumper-mongo.test.js
test/services/analyzer/expected/mongo/dumper-output/forest-simple.expected.js

fix: automatically add `fieldsToFlatten` property for mongoose projects to the generated files

---

src/services/dumper/templates/app/views/index.hbs

fix: correct HTML markup in generated view/index.html

---

test/services/analyzer/dumper.unit.test.js

chore: add expect dump calls new method

---

src/services/dumper/dumper.js
test/services/analyzer/dumper.unit.test.js

fix(dumper): ignore stats model name when generating/updating project to avoid route conflicts

---

src/renderers/environment.js
src/services/authenticator.js
src/services/environment-manager.js
src/utils/key-generator.js
test/commands/environments/create.test.js
test/commands/test-cli-helper/test-cli-context.js
test/commands/test-cli-helper/test-cli-errors.js
test/commands/test-cli-helper/test-cli.js
test/utils/key-generator.unit.test.js

feat: display the auth secret when creating an environment

---

src/services/authenticator.js
test/commands/test-cli-helper/test-cli-context.js
test/services/authenticator.unit.test.js

chore: fix usage of token path variables

---

package.json
yarn.lock

fix(security): patch semantic-release vulnerabilities

---

.github/workflows/build.yml
yarn.lock

fix(security): patch dependencies of dependencies vulnerabilities

---

yarn.lock

fix(security): patch hosted-git-info dependency vulnerabilities

---

src/commands/environments/reset.js
src/services/environment-manager.js
src/services/schema/schema-service.js
test/commands/environments/reset.test.js
test/fixtures/api.js

feat(reset): allow users to reset layout changes on a remote environment

---

src/services/branch-manager.js
test/commands/branch.test.js
test/fixtures/api.js

fix: improve error message when the user wants to create a branch on a remote branch

---

README.md

chore: update readme.md to add environments:reset details

---

src/services/logger.js
test/services/logger.unit.test.js

refactor(logger): allow to change the message color

---

src/commands/projects/create.js
src/context/command-projects-common-plan.js
src/services/schema/update/analyzer/database-analyzer.js
src/services/schema/update/analyzer/mongo-collections-analyzer.js
test/commands/projects/create.test.js
test/services/analyzer/database-analyzer-mongo.test.js
test/services/analyzer/database-analyzer.unit.test.js
test/services/analyzer/mongo-collections-analyzer.test.js

fix(mongodb): fix the onboarding cli when mongodb does't support js (#311)

---

src/services/schema/update/analyzer/mongo-collections-analyzer.js
test/services/analyzer/mongo-collections-analyzer.test.js

fix(mongodb): force to display progress bar by default

---

src/services/logger.js
test/services/logger.unit.test.js

fix(logger): allow logger to display object

---

src/commands/projects/create.js
src/services/schema/update/analyzer/mongo-collections-analyzer.js
test/services/analyzer/database-analyzer.unit.test.js
test/services/analyzer/mongo-collections-analyzer.test.js

fix(mongodb): fix typos on the "analysis" word

---

src/commands/projects/create.js
src/serializers/project.js
src/services/projects/create/project-creator.js
src/utils/event-sender.js
test/fixtures/api.js

feat: send better events during project generation

---

src/commands/projects/create.js
src/utils/event-sender.js
test/commands/projects/create.test.js
test/utils/event-sender.test.js

refactor: better track project creation errors

---

src/services/dumper/dumper.js

fix: upgrade Mongoose version in order to resolve vulnerabilities

---

src/services/api.js

refactor(force-release): remove old part of the code related to onboarding tracking

---

docker-compose.yml

chore: upgrade the docker-compose file to a newer version

---

src/commands/projects/create.js
src/serializers/project.js
src/services/projects/create/project-creator.js
test/commands/projects/create.test.js
test/fixtures/api.js
test/serializers/project.unit.test.js
test/services/project-creator.unit.test.js

chore(force-release): send new metadata about projects on creation

---

src/services/dumper/dumper.js

fix(deps): remove vulnerability on generated projects

---

src/services/dumper/templates/app/app.hbs

fix(cors): add access control allow private network handling

---

src/services/dumper/templates/app/Dockerfile.hbs

fix(dockerfile): upgrade generated dockerfile to use node 14 alpine as base

---

src/services/dumper/dumper.js

chore(force-release): upgrade generated project using express-jwt to 6.1.2

---

package.json
yarn.lock

I followed this setup:
https://github.com/ForestAdmin/forestadmin/pull/4578
It seems that everything works as expected in the frontend release actions since then.

chore(ci): patch semantic-release dependency vulnerabilities

---

src/services/authenticator.js
test/services/authenticator.unit.test.js

fix(auth): display a better error message when the provided token is empty

---

src/commands/environments/reset.js
src/commands/push.js
src/services/ask-for-environment.js

refactor: create an ask environment service

---

src/services/ask-for-environment.js

chore: enhance error on ask for environement service

---

src/commands/set-origin.js
src/services/branch-manager.js
test/commands/set-origin.test.js
test/fixtures/api.js

feat(branch): add set origin command

---

src/commands/deploy.js
src/services/environment-manager.js
test/commands/deploy.test.js

feat: user can deploy to the reference environment

---

src/commands/branch.js
src/commands/deploy.js
src/commands/push.js
src/commands/set-origin.js
src/context/renderers-plan.js
src/deserializers/branch.js
src/renderers/branches.js
src/services/branch-manager.js
src/services/environment-manager.js
test/commands/branch.test.js
test/commands/deploy.test.js
test/commands/push.test.js
test/commands/set-origin.test.js
test/fixtures/api.js

feat: handle branch origin

---

.releaserc.js

chore: add beta as a delivery branch

---

src/services/schema/update/analyzer/sequelize-table-constraints-getter.js

(See https://dba.stackexchange.com/questions/318622/query-took-50ms-on-pg11-but-500ms-on-pg12)

perf: fix performance issue on pg greater that 12 when updating models

---

src/renderers/environments.js
test/commands/environments.test.js
test/fixtures/api.js

fix: handle case when apiEndPoint is null during the onboarding

---

yarn.lock

chore(security): patch dependencies of dev dependencies vulnerabilities

---

yarn.lock

chore(security): patch moment-timezone dependency vulnerabilities

---

package.json
yarn.lock

chore(security): patch sequelize dependency vulnerabilities

---

yarn.lock

fix(security): patch jose dependency vulnerability

---

yarn.lock

fix(security): patch qs dependency vulnerabilities

---

yarn.lock

fix(security): patch got dependency vulnerability

---

.eslintrc.js
.github/workflows/build.yml
.gitignore
bin/run
jest.config.js
package.json
tsconfig.json
yarn.lock

chore(typescript): add typescript to toolbelt

---

.github/workflows/build.yml

chore(force-release): fix ci

---

.github/workflows/build.yml

chore(typescript): fix upload paths 

---

.github/workflows/build.yml

chore(typescript): fix checkout and shorten upload

---

.github/workflows/build.yml

chore(typescript): don't upload build

---

.github/workflows/build.yml

chore(force-release): update ci

---

README.md
package.json
src/commands/schema/diff.js
src/context/dependencies-plan.js
src/renderers/environment.js
src/services/environment-manager.js
src/utils/terminator.js
test/commands/schema/diff.test.js
test/fixtures/api.js
test/services/environment-manager.unit.test.js
yarn.lock

feat(schema-diff): compare two environments api map

---

src/abstract-command.js
src/commands/branch.js
src/commands/deploy.js
src/commands/environments.js
src/commands/environments/copy-layout.js
src/commands/environments/create.js
src/commands/environments/delete.js
src/commands/environments/get.js
src/commands/environments/reset.js
src/commands/environments/update.js
src/commands/init.js
src/commands/login.js
src/commands/projects.js
src/commands/projects/create.js
src/commands/projects/get.js
src/commands/push.js
src/commands/schema/apply.js
src/commands/schema/diff.js
src/commands/schema/update.js
src/commands/set-origin.js
src/commands/switch.js

refactor(oclif): properly import the flags module into each command

---

.github/workflows/build.yml

ci(build): use the same cache hash between lint and build

---

package.json
src/abstract-command.ts
yarn.lock

chore(context): upgrade library

---

src/commands/projects/create.ts
test/commands/projects/create.test.js

fix(mongo): don't use spinner when analyzing the database

---

Dockerfile

fix(docker): correctly build docker image to prevent execution error

---

src/abstract-project-create-command.ts
src/commands/projects/create.ts
src/interfaces/project-create-interface.ts
src/services/dumpers/abstract-dumper.ts
src/services/dumpers/forest-express.js
src/services/projects/create/project-creator.js
src/services/schema/update/database.js
src/utils/database-url.ts
test/abstractProjectCreateCommand.unit.test.ts
test/services/dumpers/abstract-dumper.unit.test.ts
test/services/dumpers/forest-express/dumper-mongo.test.js
test/services/dumpers/forest-express/dumper-sequelize.test.js
test/services/dumpers/forest-express/dumper-sql.test.js
test/services/dumpers/forest-express/forest-express.test.js
test/services/dumpers/forest-express/forest-express.unit.test.js
test/services/project-creator.unit.test.js

refactor(interface): improve project creation typescript interface

---

src/commands/branch.js
src/commands/deploy.js
src/commands/push.js
src/commands/set-origin.js
src/commands/switch.js
src/deserializers/api-error.js
src/services/branch-manager.js
src/utils/error.js
test/commands/deploy.test.js
test/commands/switch.test.js
test/fixtures/api.js

feat: run diff command when push or deploy fails

---

src/services/schema/schema-service.js

fix(update): add back support of outputDirectory option

---

jest.config.js
tsconfig.json

fix(node10): change build target to correctly support node10

---

src/serializers/schema.js
src/services/apimap-sorter.js
src/services/dumpers/forest-express.js
src/services/project-manager.js
src/services/schema/update/analyzer/mongo-hasmany-analyzer.js
src/services/schema/update/analyzer/mongo-references-analyzer.js
src/services/schema/update/analyzer/sequelize-tables-analyzer.js
src/utils/fields.js
src/utils/strings.ts
test/services/analyzer/database-analyzer-sequelize.test.js
test/services/analyzer/fixtures/mongo/hasmany-model.js
test/services/analyzer/fixtures/mongo/many-nulls-model.js
test/services/analyzer/fixtures/mongo/many-objectid-fields-model.js
test/services/analyzer/fixtures/mongo/multiple-references-same-field-model.js
test/services/analyzer/fixtures/mongo/simple-model.js
test/services/analyzer/sequelize-tables-analyzer.test.js
test/services/dumpers/forest-express/forest-express.unit.test.js
test/utils/fields.test.js
tsconfig.json

refactor(lodash): move lodash in context

---

src/services/dumpers/forest-express.js
test/services/dumpers/forest-express/forest-express.unit.test.js

fix(schema:update): properly retrieve the export path of the models when using multiple databases

---

src/commands/projects/get.ts
src/context/env-plan.js
src/services/api.js
src/services/branch-manager.js
src/services/dumpers/forest-express.js
src/services/environment-manager.js
src/services/job-state-checker.js
src/services/oidc/authenticator.js
src/services/project-manager.js
src/services/schema-sender.js
src/utils/event-sender.js
test/commands/test-cli-helper/test-cli-context.js
test/fixtures/env.js
test/services/api.unit.test.js
test/services/dumpers/forest-express/forest-express.test.js
test/services/dumpers/forest-express/forest-express.unit.test.js
test/services/oidc/authenticator.unit.test.js
test/utils/event-sender.test.js

refactor(consistency): use `FOREST_SERVER_URL` instead of `FOREST_URL`

---

src/abstract-project-create-command.ts
src/commands/projects/create.ts
src/interfaces/command-create-project-arguments-interface.ts
src/services/dumpers/forest-express.js
src/services/projects/create/command-generate-config-getter.js
src/services/prompter/database-prompts.js
src/services/prompter/general-prompter.js
test/abstractProjectCreateCommand.unit.test.ts

refactor(arguments): allow to specify which arguments should be used for every project creation command

---

src/abstract-project-create-command.ts
src/commands/projects/create.ts
src/interfaces/command-create-project-arguments-interface.ts
test/abstractProjectCreateCommand.unit.test.ts

refactor(syntax): uppercase interface name

---

src/utils/database-url.ts
test/utils/database-url.unit.test.js

fix(database-url): properly build urls without username nor passport

---

src/services/prompter/database-prompts.js
test/services/prompter/database-prompts.test.js

fix(mongoose-command): don't ask for dialect on nosql dumper

---

src/services/prompter/database-prompts.js
test/services/prompter/database-prompts.test.js

fix(prompter): correctly handle prompts and default value is the database dialect is already known

---

src/commands/projects/create/sql.ts
test/commands/projects/create/sql.test.js

feat(projects:create): add new command to generate sql projects for agent-nodejs

---

src/commands/projects/create/nosql.ts
src/services/schema/update/database.js
test/commands/projects/create/nosql.test.js

https://app.clickup.com/t/860puxe73

feat(projects:create): add new command to generate nosql projects for agent-nodejs

---

src/services/dumpers/agent-nodejs.ts
test/services/dumpers/agent-nodejs/agent-nodejs-dumper-mongoose-models.test.ts
test/services/dumpers/agent-nodejs/agent-nodejs.unit.test.ts
test/services/dumpers/agent-nodejs/expected/mongodb/index.js

fix(agent-nodejs): remove unnecessary primary folder for mongoose datasource

---

src/services/dumpers/templates/agent-nodejs/javascript/models/index.hbs
test/services/dumpers/agent-nodejs/expected/javascript/mongo-models/index.expected.js

fix(agent-nodejs): remove deprecated connection options on mongoose dumper

---

src/services/dumpers/agent-nodejs.ts
test/services/dumpers/agent-nodejs/agent-nodejs.unit.test.ts
test/services/dumpers/agent-nodejs/expected/javascript/mariadb/index.js
test/services/dumpers/agent-nodejs/expected/javascript/mssql/index.js
test/services/dumpers/agent-nodejs/expected/javascript/mysql/index.js
test/services/dumpers/agent-nodejs/expected/javascript/postgres/index.js

fix(agent-nodejs): properly pass the dialect options

---

src/services/dumpers/agent-nodejs.ts
src/services/dumpers/templates/agent-nodejs/javascript/index.hbs
src/services/dumpers/templates/agent-nodejs/typescript/index.hbs
test/services/dumpers/agent-nodejs/agent-nodejs.unit.test.ts
test/services/dumpers/agent-nodejs/expected/typescript/mariadb/index.ts
test/services/dumpers/agent-nodejs/expected/typescript/mssql/index.ts
test/services/dumpers/agent-nodejs/expected/typescript/mysql/index.ts
test/services/dumpers/agent-nodejs/expected/typescript/postgres/index.ts

chore(dumper): move datasource management from code to template

---

src/services/dumpers/agent-nodejs.ts
src/services/dumpers/templates/agent-nodejs/typescript/models/index.hbs
src/services/dumpers/templates/agent-nodejs/typescript/models/model.hbs
src/utils/handlebars/helpers/and.ts
src/utils/handlebars/helpers/capitalise.ts
src/utils/handlebars/helpers/to-interface-type.ts
src/utils/handlebars/loader.js
src/utils/handlebars/partials/render-nested-interface.js
test/services/dumpers/agent-nodejs/agent-nodejs-dumper-mongoose-models.test.ts
test/services/dumpers/agent-nodejs/agent-nodejs.unit.test.ts
test/services/dumpers/agent-nodejs/expected/typescript/mongo-models/deep-nested.expected.ts
test/services/dumpers/agent-nodejs/expected/typescript/mongo-models/hasmany.expected.ts
test/services/dumpers/agent-nodejs/expected/typescript/mongo-models/index.expected.ts
test/services/dumpers/agent-nodejs/expected/typescript/mongo-models/many-object-id-fields.expected.ts
test/services/dumpers/agent-nodejs/expected/typescript/mongo-models/sub-documents-ambiguous-ids.expected.ts
test/services/dumpers/agent-nodejs/expected/typescript/mongo-models/sub-documents-no-ids.expected.ts
test/services/dumpers/agent-nodejs/expected/typescript/mongo-models/sub-documents-with-ids.expected.ts
test/utils/handlebars/helpers/and.unit.test.ts
test/utils/handlebars/helpers/capitalise.unit.test.ts
test/utils/handlebars/helpers/to-interface-type.unit.test.ts
test/utils/handlebars/helpers/wrap-special-characters.unit.test.ts

feat(agent-nodejs): generate typescript mongoose models

---

package.json
yarn.lock

chore(context): upgrade to 1.37.0

---

package.json
yarn.lock

chore(context): upgrade to 1.37.1 - deprecate inject

---

src/abstract-project-create-command.ts
src/commands/projects/create/nosql.ts
src/commands/projects/create/sql.ts
src/interfaces/command-create-project-arguments-interface.ts
src/services/projects/create/command-generate-config-getter.js
src/services/prompter/application-prompts.js
src/utils/languages.ts
test/abstractProjectCreateCommand.unit.test.ts
test/commands/projects/create/nosql.test.js
test/commands/projects/create/sql.test.js
test/services/command-generate-config-getter.test.js
test/services/prompter/application-prompts.test.js

feat(agent-nodejs): allow users to generate a project in typescript

---

src/services/dumpers/templates/agent-nodejs/common/env.hbs
src/services/dumpers/templates/agent-nodejs/javascript/index.hbs
test/services/dumpers/agent-nodejs/expected/javascript/mariadb/env
test/services/dumpers/agent-nodejs/expected/javascript/mariadb/index.js
test/services/dumpers/agent-nodejs/expected/javascript/mongodb/env
test/services/dumpers/agent-nodejs/expected/javascript/mongodb/index.js
test/services/dumpers/agent-nodejs/expected/javascript/mssql/env
test/services/dumpers/agent-nodejs/expected/javascript/mssql/index.js
test/services/dumpers/agent-nodejs/expected/javascript/mysql/env
test/services/dumpers/agent-nodejs/expected/javascript/mysql/index.js
test/services/dumpers/agent-nodejs/expected/javascript/postgres/env
test/services/dumpers/agent-nodejs/expected/javascript/postgres/index.js
test/services/dumpers/agent-nodejs/expected/typescript/mariadb/env
test/services/dumpers/agent-nodejs/expected/typescript/mongodb/env
test/services/dumpers/agent-nodejs/expected/typescript/mssql/env
test/services/dumpers/agent-nodejs/expected/typescript/mysql/env
test/services/dumpers/agent-nodejs/expected/typescript/postgres/env

feat(agent-nodejs): unify javascript and typescript generated code and .env

---

docker-compose.yml

chore(docker-file): let docker choose the network adapter in dev

---

.github/workflows/build.yml

ci: update ci workflow to match common configuration

---

src/services/projects/create/project-creator.js

refactor(typing): fix jsdoc typing of projectCreator.create()

---

.github/workflows/build.yml
package.json
src/context/logger-plan.js
src/hooks/init/check-compatible-node-version.ts
tsconfig.json
yarn.lock

BREAKING CHANGE: users will have to upgrade to Node.js version 14+ to ensure a full compatibility

feat(node): end the support of Node.js versions 10, 11, 12, 13

---

src/services/projects/create/options.ts
src/utils/option-parser.ts
test/commands/test-cli-helper/test-cli-context.js
test/commands/test-cli-helper/test-cli-errors.js

fix(project-creation): prompt for database schema when only --databaseConnectionURL flag is given

---

CHANGELOG.md
package.json
src/utils/option-parser.ts
test/commands/test-cli-helper/test-cli-context.js
test/commands/test-cli-helper/test-cli-errors.js

chore: merge main into beta

---

src/commands/environments/create.js
src/serializers/environment.js
src/services/environment-manager.js
test/fixtures/api.js

feat(environments): allow to disable roles when creating an environment

---

yarn.lock

fix(security): patch dottie dependency vulnerabilities

---

.github/workflows/build.yml
package.json
yarn.lock

fix(security): patch semver dependency vulnerabilities

---

package.json
yarn.lock

fix(security): patch mongodb dependency vulnerabilities

---

src/services/dumpers/forest-express.js
test/services/dumpers/forest-express/forest-express.unit.test.js

fix(schema:update): correct a typo in an instruction

---

package.json
yarn.lock

chore(deps): bump sequelize from 5.22.5 to 6.32.1

---

src/services/dumpers/forest-express.js

feat: generate old project with latest version of forest-express-xxx

---

src/serializers/schema.js

fix: fix schema serialization on schema:apply for SA field hook property

---

src/services/schema/update/analyzer/mongo-collections-analyzer.js
test/services/analyzer/mongo-collections-analyzer.test.js

fix(onboarding): users can now onboard on cosmos nosql databases

---

.github/workflows/build.yml

fix: bump semantic release to allow node version 18

---

package.json
src/commands/schema/apply.js
src/context/dependencies-plan.js
test/commands/schema/apply.test.js
test/services/authenticator.unit.test.js
yarn.lock

fix: warning logs during install due to joi

---

package.json
src/services/environment-manager.js
src/services/job-state-checker.js
src/services/project-manager.js
src/services/schema-sender.js
yarn.lock

fix: warning during install due to superagent

---

yarn.lock

fix(security): patch es5-ext dependency vulnerabilities

---

package.json
src/context/dependencies-plan.js
test/services/authenticator.unit.test.js
yarn.lock

fix(dependencies): remove warning caused by @hapi/joi

---

src/services/dumpers/templates/agent-nodejs/javascript/index.hbs
src/services/dumpers/templates/agent-nodejs/typescript/index.hbs
test/services/dumpers/agent-nodejs/expected/javascript/mariadb/index.js
test/services/dumpers/agent-nodejs/expected/javascript/mongodb/index.js
test/services/dumpers/agent-nodejs/expected/javascript/mssql/index.js
test/services/dumpers/agent-nodejs/expected/javascript/mysql/index.js
test/services/dumpers/agent-nodejs/expected/javascript/postgres/index.js
test/services/dumpers/agent-nodejs/expected/typescript/mariadb/index.ts
test/services/dumpers/agent-nodejs/expected/typescript/mongodb/index.ts
test/services/dumpers/agent-nodejs/expected/typescript/mssql/index.ts
test/services/dumpers/agent-nodejs/expected/typescript/mysql/index.ts
test/services/dumpers/agent-nodejs/expected/typescript/postgres/index.ts

fix: typos in generated projects

---

yarn.lock

fix(security): patch ws dependency vulnerabilities

---

.github/workflows/build.yml

chore: update test run to latest docker command

---

yarn.lock

fix(security): patch fast-xml-parser dependency vulnerabilities

---

src/abstract-project-create-command.ts
src/commands/projects/bundle/nosql.ts
src/commands/projects/bundle/sql.ts

feat: add bundle project command to simplify agent-nodejs migration

---

package.json
src/services/oidc/authenticator.ts
yarn.lock

fix(vulnerability): bump openid-client version

---

package.json
src/services/dumpers/agent-nodejs.ts
src/services/dumpers/forest-express.js
test/services/dumpers/agent-nodejs/agent-nodejs.unit.test.ts
test/services/dumpers/agent-nodejs/expected/javascript/mssql/package.json
test/services/dumpers/agent-nodejs/expected/typescript/mssql/package.json
yarn.lock

chore(dep): bump tedious

---

package.json
yarn.lock

chore(dep): fix ip vulnerability
